import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: theme.background,
    },
    topBar: {
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#ffffff12',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    backButton: {
        width: 38,
        height: 38,
        borderRadius: 11,
        borderWidth: 1,
        borderColor: '#ffffff22',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#0d0f14',
    },
    backButtonText: {
        color: theme.foreground,
        fontSize: 18,
        fontWeight: '700',
        marginTop: -2,
    },
    topTitleWrap: {
        flex: 1,
    },
    topTitle: {
        color: theme.foreground,
        fontSize: 21,
        fontWeight: '700',
    },
    topSubTitle: {
        color: '#8f8f99',
        fontSize: 13,
        marginTop: 2,
    },
    rolePill: {
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#ffffff30',
        backgroundColor: '#ffffff14',
    },
    rolePillText: {
        color: '#f5f5f5',
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    scrollArea: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 14,
        paddingTop: 14,
        paddingBottom: 34,
    },
    storageCard: {
        backgroundColor: '#0d1016',
        borderWidth: 1,
        borderColor: '#ffffff14',
        borderRadius: 14,
        padding: 14,
    },
    rowBetween: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    storageLabel: {
        color: '#9c9ca7',
        fontSize: 13,
    },
    storageValue: {
        color: '#ececf2',
        fontSize: 15,
        fontWeight: '600',
    },
    progressTrack: {
        marginTop: 10,
        height: 7,
        borderRadius: 999,
        backgroundColor: '#ffffff12',
        overflow: 'hidden',
    },
    progressFill: {
        height: 7,
        borderRadius: 999,
        backgroundColor: '#f5f5f5',
    },
    remainingText: {
        color: '#8d8d97',
        fontSize: 12,
        marginTop: 8,
    },
    proButton: {
        marginTop: 12,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: '#ffffff26',
        backgroundColor: '#ffffff14',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    proButtonDisabled: {
        opacity: 0.5,
    },
    proButtonText: {
        color: '#f5f5f5',
        fontSize: 14,
        fontWeight: '600',
    },
    proButtonMeta: {
        color: '#f5f5f5',
        fontSize: 13,
    },
    sectionHeader: {
        marginTop: 16,
        marginBottom: 8,
        paddingHorizontal: 2,
    },
    sectionTitle: {
        color: '#e7e7ef',
        fontSize: 20,
        fontWeight: '700',
    },
    folderGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    folderCard: {
        width: '31%',
        minHeight: 108,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#ffffff14',
        backgroundColor: '#0d1016',
        padding: 10,
        justifyContent: 'space-between',
    },
    folderIconChip: {
        width: 32,
        height: 32,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
    },
    folderIconText: {
        fontSize: 14,
        fontWeight: '700',
    },
    folderName: {
        color: '#ececf2',
        fontSize: 14,
        fontWeight: '600',
        marginTop: 8,
    },
    folderCount: {
        color: '#8d8d97',
        fontSize: 12,
    },
    colorEditPill: {
        marginTop: 4,
        alignSelf: 'flex-start',
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#ffffff22',
        backgroundColor: '#ffffff12',
    },
    colorEditPillText: {
        color: '#ececf2',
        fontSize: 11,
        fontWeight: '600',
    },
    fileCard: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#ffffff14',
        backgroundColor: '#0d1016',
        paddingHorizontal: 12,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    fileLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    fileIconWrap: {
        width: 30,
        height: 30,
        borderRadius: 9,
        backgroundColor: '#151823',
        borderWidth: 1,
        borderColor: '#ffffff1c',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fileIcon: {
        color: '#9ea0aa',
        fontSize: 11,
        fontWeight: '700',
    },
    fileName: {
        color: '#ececf2',
        fontSize: 16,
        fontWeight: '600',
    },
    fileMeta: {
        color: '#8d8d97',
        fontSize: 12,
        marginTop: 2,
    },
    fileMore: {
        color: '#9fa1ab',
        fontSize: 18,
        fontWeight: '700',
        paddingHorizontal: 6,
    },
    notesCard: {
        marginTop: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#ffffff14',
        backgroundColor: '#0d1016',
        padding: 12,
    },
    notesTitle: {
        color: '#ececf2',
        fontSize: 20,
        fontWeight: '700',
    },
    notesMode: {
        color: '#8d8d97',
        fontSize: 12,
        marginTop: 4,
        marginBottom: 8,
    },
    notesBody: {
        color: '#9a9aa4',
        fontSize: 14,
        lineHeight: 20,
    },
});
